spring:
  datasource:
#   数据源基本配置
    username: root
    password: 311
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.71.48:3306/library
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: 39.108.71.48
  data:
    solr:
      host: http://www.tiannoyi.com/solr
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
mybatis:
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml
server:
  tomcat:
    uri-encoding: utf-8
thymeleaf:
           cache: falseo
shiro:
  loginUrl: /login
  successUrl: /hello
  unauthorizedUrl: /error
pagehelper:
  page-size-zero: true
  reasonable: true
logging:
  level:
     com.hniu.mapper: debug
web:
  upload-path: C:/books/upload/images/
#http://www.tiannoyi.com/ 上线时请改为这个地址...
  imagePath: http://localhost:8080/


